"""
backend/api/agents.py

REST endpoints for AI Data Agent alerts.

Routes:
  GET  /api/v1/agents/alerts           — list active alerts for this org/workspace
  POST /api/v1/agents/run              — manually trigger all agents now
  DELETE /api/v1/agents/alerts/{id}/dismiss — dismiss (soft-delete) an alert
"""
import logging

from fastapi import APIRouter, Query, Request

from backend.agents.agent_store import get_alerts, dismiss_alert
from backend.event_bus import recent_events
from backend.agents import (
    insight_agent,
    anomaly_agent,
    risk_agent,
    schema_agent,
)

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/v1/agents", tags=["agents"])


@router.get("/events")
def list_events(
    request: Request,
    limit: int = Query(50, ge=1, le=200),
    event_type: str | None = Query(None),
):
    """Return recent Data Intelligence Bus events for this org/workspace."""
    org_id = getattr(request.state, "org_id", None)
    workspace_id = getattr(request.state, "workspace_id", None)
    events = recent_events(
        limit=limit,
        org_id=org_id,
        workspace_id=workspace_id,
        event_type=event_type,
    )
    return {"events": events, "total": len(events)}


@router.get("/alerts")
def list_alerts(
    request: Request,
    limit: int = Query(50, ge=1, le=200),
    include_dismissed: bool = Query(False),
):
    """Return recent AI Data Agent alerts for the current org/workspace."""
    org_id = getattr(request.state, "org_id", None)
    workspace_id = getattr(request.state, "workspace_id", None)
    alerts = get_alerts(
        org_id=org_id,
        workspace_id=workspace_id,
        limit=limit,
        include_dismissed=include_dismissed,
    )
    return {"alerts": alerts, "total": len(alerts)}


@router.post("/run")
def trigger_run(request: Request):
    """
    Manually trigger all AI Data Agents for the current workspace.
    Returns the count of new alerts generated by each agent.
    """
    org_id = getattr(request.state, "org_id", None)
    workspace_id = getattr(request.state, "workspace_id", None)

    results: dict[str, dict] = {}
    for name, module in [
        ("insight", insight_agent),
        ("anomaly", anomaly_agent),
        ("risk",    risk_agent),
        ("schema",  schema_agent),
    ]:
        try:
            new = module.run(org_id=org_id, workspace_id=workspace_id)
            results[name] = {"new_alerts": len(new)}
            logger.info(f"[AgentsAPI] manual run: {name} → {len(new)} new alert(s)")
        except Exception as exc:
            logger.warning(f"[AgentsAPI] {name} error: {exc}")
            results[name] = {"error": str(exc)}

    total_new = sum(r.get("new_alerts", 0) for r in results.values())
    return {"status": "ok", "total_new_alerts": total_new, "results": results}


@router.delete("/alerts/{alert_id}/dismiss")
def dismiss(alert_id: str, request: Request):
    """Mark an alert as dismissed (soft delete)."""
    ok = dismiss_alert(alert_id)
    return {"success": ok, "alert_id": alert_id}
