"""VoxCore Engine - Main governance and validation logic"""

import logging
from enum import Enum
from dataclasses import dataclass, field
from typing import Optional, Dict, Any, List
import time

logger = logging.getLogger(__name__)


class ExecutionStatus(Enum):
    """Query execution status"""
    SUCCESS = "success"
    REWRITTEN = "rewritten"
    BLOCKED = "blocked"
    ERROR = "error"


@dataclass
class ValidationResult:
    """Result of SQL validation"""
    is_valid: bool
    was_rewritten: bool
    risk_score: int = 0
    issues: List[str] = field(default_factory=list)
    original_sql: str = ""
    rewritten_sql: str = ""


@dataclass
class ExecutionLog:
    """Complete execution log with all metadata"""
    query_id: str
    question: str
    generated_sql: str
    final_sql: str
    platform: str
    user_id: str
    status: ExecutionStatus
    validation: Optional[ValidationResult] = None
    rows_returned: int = 0
    execution_time_ms: float = 0.0
    error: Optional[str] = None
    timestamp: float = field(default_factory=time.time)


class VoxCoreEngine:
    """Main VoxCore governance engine"""
    
    def __init__(self):
        self.query_counter = 0
        logger.info("VoxCoreEngine initialized")
    
    def execute_query(
        self,
        question: str,
        generated_sql: str,
        platform: str,
        user_id: str,
        connection=None,
    ) -> ExecutionLog:
        """
        Execute a query with full governance:
        1. Check for destructive operations (block if found)
        2. Validate SQL syntax
        3. Rewrite SQL if needed for platform compatibility
        4. Execute and return results
        
        Args:
            question: Original natural language question
            generated_sql: SQL generated by LLM
            platform: Target platform (sqlserver, snowflake, postgres, etc.)
            user_id: User executing the query
            connection: Database connection object
            
        Returns:
            ExecutionLog with all metadata
        """
        self.query_counter += 1
        query_id = f"query_{self.query_counter}_{int(time.time() * 1000)}"
        
        logger.info(f"[{query_id}] Starting execution")
        logger.info(f"  Question: {question}")
        logger.info(f"  Platform: {platform}")
        logger.info(f"  User: {user_id}")
        
        start_time = time.time()
        
        try:
            # STEP 1: Check for destructive operations
            if self._check_destructive(generated_sql):
                logger.warning(f"[{query_id}] BLOCKED: Destructive operation detected")
                return ExecutionLog(
                    query_id=query_id,
                    question=question,
                    generated_sql=generated_sql,
                    final_sql=generated_sql,
                    platform=platform,
                    user_id=user_id,
                    status=ExecutionStatus.BLOCKED,
                    error="DROP, DELETE, TRUNCATE, and ALTER operations are not allowed",
                    validation=ValidationResult(
                        is_valid=False,
                        was_rewritten=False,
                        risk_score=100,
                        issues=["Destructive operation blocked"],
                    ),
                )
            
            # STEP 2: Validate and rewrite SQL for platform
            validation = self._validate_and_rewrite(generated_sql, platform)
            final_sql = validation.rewritten_sql if validation.was_rewritten else generated_sql
            
            logger.info(f"[{query_id}] Validation complete")
            logger.info(f"  Valid: {validation.is_valid}")
            logger.info(f"  Rewritten: {validation.was_rewritten}")
            logger.info(f"  Risk score: {validation.risk_score}")
            
            if not validation.is_valid:
                logger.warning(f"[{query_id}] Validation failed: {validation.issues}")
                return ExecutionLog(
                    query_id=query_id,
                    question=question,
                    generated_sql=generated_sql,
                    final_sql=final_sql,
                    platform=platform,
                    user_id=user_id,
                    status=ExecutionStatus.ERROR,
                    validation=validation,
                    error=f"Validation failed: {'; '.join(validation.issues)}",
                )
            
            # STEP 3: Execute query if connection provided
            rows_returned = 0
            if connection:
                try:
                    cursor = connection.cursor()
                    cursor.execute(final_sql)
                    rows_returned = len(cursor.fetchall()) if cursor.description else 0
                    cursor.close()
                    logger.info(f"[{query_id}] Query executed: {rows_returned} rows")
                except Exception as e:
                    logger.error(f"[{query_id}] Execution error: {e}")
                    return ExecutionLog(
                        query_id=query_id,
                        question=question,
                        generated_sql=generated_sql,
                        final_sql=final_sql,
                        platform=platform,
                        user_id=user_id,
                        status=ExecutionStatus.ERROR,
                        validation=validation,
                        error=str(e),
                    )
            
            # STEP 4: Return success
            execution_time_ms = (time.time() - start_time) * 1000
            status = ExecutionStatus.REWRITTEN if validation.was_rewritten else ExecutionStatus.SUCCESS
            
            logger.info(f"[{query_id}] Complete: {status.value} ({execution_time_ms:.2f}ms)")
            
            return ExecutionLog(
                query_id=query_id,
                question=question,
                generated_sql=generated_sql,
                final_sql=final_sql,
                platform=platform,
                user_id=user_id,
                status=status,
                validation=validation,
                rows_returned=rows_returned,
                execution_time_ms=execution_time_ms,
            )
        
        except Exception as e:
            logger.error(f"[{query_id}] Unexpected error: {e}")
            import traceback
            traceback.print_exc()
            
            execution_time_ms = (time.time() - start_time) * 1000
            return ExecutionLog(
                query_id=query_id,
                question=question,
                generated_sql=generated_sql,
                final_sql=generated_sql,
                platform=platform,
                user_id=user_id,
                status=ExecutionStatus.ERROR,
                error=str(e),
                execution_time_ms=execution_time_ms,
            )
    
    def _check_destructive(self, sql: str) -> bool:
        """Check if SQL contains destructive operations"""
        dangerous_keywords = ["DROP", "DELETE", "TRUNCATE", "ALTER TABLE"]
        sql_upper = sql.upper().strip()
        
        for keyword in dangerous_keywords:
            if sql_upper.startswith(keyword):
                return True
        
        return False
    
    def _validate_and_rewrite(self, sql: str, platform: str) -> ValidationResult:
        """
        Validate SQL and rewrite for target platform if needed
        
        For now, this is a simple implementation.
        In production, this would:
        - Parse SQL AST
        - Check against schema
        - Rewrite for platform-specific syntax
        - Calculate risk score
        """
        issues = []
        was_rewritten = False
        rewritten_sql = sql
        
        # Platform-specific rewrites
        if platform.lower() == "sqlserver":
            # LIMIT → TOP
            if "LIMIT" in sql.upper():
                rewritten_sql = self._rewrite_limit_to_top(sql)
                was_rewritten = True
                logger.info(f"Rewrote LIMIT to TOP for SQL Server")
        
        # Calculate risk score (0-100)
        risk_score = self._calculate_risk_score(sql, platform)
        
        return ValidationResult(
            is_valid=True,
            was_rewritten=was_rewritten,
            risk_score=risk_score,
            issues=issues,
            original_sql=sql,
            rewritten_sql=rewritten_sql,
        )
    
    def _rewrite_limit_to_top(self, sql: str) -> str:
        """Rewrite LIMIT clause to TOP for SQL Server"""
        import re
        
        # Match LIMIT N at end of query
        pattern = r'\bLIMIT\s+(\d+)\s*$'
        match = re.search(pattern, sql, re.IGNORECASE)
        
        if match:
            limit_value = match.group(1)
            # Remove LIMIT clause
            sql_without_limit = re.sub(pattern, '', sql, flags=re.IGNORECASE)
            
            # Add TOP clause after SELECT
            select_pattern = r'(SELECT)\s+'
            rewritten = re.sub(select_pattern, f'SELECT TOP {limit_value} ', sql_without_limit, flags=re.IGNORECASE, count=1)
            
            return rewritten
        
        return sql
    
    def _calculate_risk_score(self, sql: str, platform: str) -> int:
        """Calculate risk score for SQL (0-100)"""
        score = 0
        sql_upper = sql.upper()
        
        # Check for various risk factors
        if "UNION" in sql_upper:
            score += 10
        if "SUBQUERY" in sql_upper or "(" in sql and "SELECT" in sql_upper:
            score += 5
        if "JOIN" in sql_upper:
            score += 5
        if "GROUP BY" in sql_upper:
            score += 3
        if "HAVING" in sql_upper:
            score += 3
        
        return min(score, 100)


# Global VoxCore instance
_voxcore_instance = None


def get_voxcore() -> VoxCoreEngine:
    """Get or create the global VoxCore instance"""
    global _voxcore_instance
    if _voxcore_instance is None:
        _voxcore_instance = VoxCoreEngine()
    return _voxcore_instance
