export function runEMD(data: any[], type: string) {
  const insights: string[] = [];

  if (!data || data.length === 0) {
    return {
      insights: ["No data available"],
      summary: "No insights could be generated.",
      riskLevel: "LOW",
    };
  }

  // 🏆 TOP PERFORMER
  if (type === "sales") {
    const max = data.reduce((a, b) => (b.revenue > a.revenue ? b : a));
    insights.push(
      `${max.month} generated the highest revenue at $${max.revenue}.`
    );

    // 📈 GROWTH
    const first = data[0].revenue;
    const last = data[data.length - 1].revenue;
    const growth = ((last - first) / first) * 100;

    if (growth > 0) {
      insights.push(
        `Revenue increased ${growth.toFixed(1)}% over the selected period.`
      );
    }

    // 📉 DECLINE
    if (growth < 0) {
      insights.push(
        `Revenue declined ${Math.abs(growth).toFixed(
          1
        )}% over the selected period.`
      );
    }

    // ⚠️ ANOMALY
    const avg =
      data.reduce((sum, d) => sum + d.revenue, 0) / data.length;

    const anomaly = data.find(d => d.revenue > avg * 1.8);

    if (anomaly) {
      insights.push(
        `Unusual spike detected in ${anomaly.month} (${anomaly.revenue}).`
      );
    }
  }

  // 👥 USERS
  if (type === "users") {
    const total = data.length;
    insights.push(`Dataset contains ${total} users.`);

    const admins = data.filter(u => u.role === "Admin").length;
    insights.push(`${admins} users have admin-level access.`);

    if (admins > total * 0.4) {
      insights.push("⚠️ High number of admin users detected.");
    }
  }

  // ⚠️ DANGEROUS QUERY
  if (type === "danger") {
    insights.push(
      "⚠️ This query contains potentially destructive operations."
    );
    return {
      insights,
      summary:
        "High-risk query detected. Execution could result in data loss.",
      riskLevel: "HIGH",
    };
  }

  return {
    insights,
    summary: "Automated insights generated by VoxCore EMD.",
    riskLevel: "LOW",
  };
}
